#!/usr/bin/env python3
"""Generate a PR packet from local repo state for GITWIZ."""

from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


def utcnow_compact() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H%M%SZ")


def utcnow_display() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def run_git(repo_path: Path, args: list[str], check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=repo_path,
        check=check,
        text=True,
        capture_output=True,
    )


def detect_repo_root(explicit_root: str | None) -> Path:
    if explicit_root:
        return Path(explicit_root).expanduser().resolve()
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        check=True,
        text=True,
        capture_output=True,
    )
    return Path(result.stdout.strip()).resolve()


def choose_title(repo_name: str, branch: str, commits: list[dict[str, str]], dirty: bool, explicit_title: str | None) -> str:
    if explicit_title:
        return explicit_title
    if len(commits) == 1 and not dirty:
        return commits[0]["subject"]
    branch_hint = branch if branch not in {"HEAD", "main"} else repo_name
    return f"Sync local project state for {branch_hint}"


def markdown_packet(packet: dict[str, object]) -> str:
    commits = packet["commits"]  # type: ignore[assignment]
    file_changes = packet["file_changes"]  # type: ignore[assignment]
    local_status = packet["local_status"]  # type: ignore[assignment]
    lines = [
        f"# {packet['title']}",
        "",
        f"Generated: {packet['generated_at_utc']}",
        "",
        "## Summary",
        "",
        f"- Repo: `{packet['repo_name']}`",
        f"- Repo path: `{packet['repo_path']}`",
        f"- Head branch: `{packet['head_branch']}`",
        f"- Base ref: `{packet['base_ref']}`",
        f"- Base commit: `{packet['base_commit']}`",
        f"- Head commit: `{packet['head_commit']}`",
        f"- Commits in range: `{len(commits)}`",
        f"- Working tree dirty: `{packet['dirty']}`",
        "",
        "## Suggested PR Body",
        "",
        "### Why",
        "",
        f"Sync the local `{packet['repo_name']}` repo state to GitHub so the remote reflects the current audited project state.",
        "",
        "### What Changed",
        "",
    ]
    if commits:
        for commit in commits:
            lines.append(f"- {commit['sha'][:7]} {commit['subject']}")
    else:
        lines.append("- No committed delta between base and head.")

    if file_changes:
        lines.extend(["", "### File Delta", ""])
        for line in file_changes[:60]:
            lines.append(f"- `{line}`")

    if local_status:
        lines.extend(["", "### Local Working Tree Notes", ""])
        for line in local_status[:40]:
            lines.append(f"- `{line}`")

    lines.extend(
        [
            "",
            "### Validation Notes",
            "",
            "- Generated by `gitwiz_pr_packet.py`.",
            "- Review for repo-specific context before opening the PR.",
            "",
            "## Machine Metadata",
            "",
            "```json",
            json.dumps(
                {
                    "base_ref": packet["base_ref"],
                    "base_commit": packet["base_commit"],
                    "head_branch": packet["head_branch"],
                    "head_commit": packet["head_commit"],
                    "pr_ready": packet["pr_ready"],
                },
                indent=2,
            ),
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-path", help="Target repo path. Defaults to current git toplevel.")
    parser.add_argument("--repo-name", default="root", help="Human-readable repo name for the packet.")
    parser.add_argument("--base", default="origin/main", help="Base ref to compare against.")
    parser.add_argument("--head", help="Head ref or branch. Defaults to the current branch.")
    parser.add_argument("--title", help="Explicit PR title override.")
    parser.add_argument("--output-dir", help="Directory to write JSON and Markdown packets into.")
    args = parser.parse_args()

    repo_root = detect_repo_root(args.repo_path)
    head_branch = args.head or run_git(repo_root, ["rev-parse", "--abbrev-ref", "HEAD"]).stdout.strip()
    head_commit = run_git(repo_root, ["rev-parse", head_branch]).stdout.strip()
    base_commit = run_git(repo_root, ["rev-parse", args.base]).stdout.strip()

    log_output = run_git(repo_root, ["log", "--format=%H%x09%s", f"{args.base}..{head_branch}"]).stdout
    commits = []
    for line in log_output.splitlines():
        if not line.strip():
            continue
        sha, subject = line.split("\t", 1)
        commits.append({"sha": sha, "subject": subject})
    commits.reverse()

    diff_stat = run_git(repo_root, ["diff", "--stat", "--find-renames", f"{args.base}..{head_branch}"], check=False).stdout
    file_delta = run_git(repo_root, ["diff", "--name-status", "--find-renames", f"{args.base}..{head_branch}"], check=False).stdout
    local_status = run_git(repo_root, ["status", "--short"], check=False).stdout

    dirty = bool(local_status.strip())
    title = choose_title(args.repo_name, head_branch, commits, dirty, args.title)
    pr_ready = head_branch not in {"HEAD", "main"} and bool(commits)

    packet = {
        "generated_at_utc": utcnow_display(),
        "generated_at_compact": utcnow_compact(),
        "repo_name": args.repo_name,
        "repo_path": str(repo_root),
        "base_ref": args.base,
        "base_commit": base_commit,
        "head_branch": head_branch,
        "head_commit": head_commit,
        "title": title,
        "dirty": dirty,
        "pr_ready": pr_ready,
        "commits": commits,
        "diff_stat": [line for line in diff_stat.splitlines() if line.strip()],
        "file_changes": [line for line in file_delta.splitlines() if line.strip()],
        "local_status": [line for line in local_status.splitlines() if line.strip()],
    }

    if args.output_dir:
        output_dir = Path(args.output_dir).expanduser().resolve()
    else:
        output_dir = repo_root / "reports" / "analysis" / "gitwiz"
    output_dir.mkdir(parents=True, exist_ok=True)

    stem = f"GITWIZ_PR_PACKET__{packet['generated_at_compact']}"
    json_path = output_dir / f"{stem}.json"
    md_path = output_dir / f"{stem}.md"
    json_path.write_text(json.dumps(packet, indent=2), encoding="utf-8")
    md_path.write_text(markdown_packet(packet), encoding="utf-8")

    print(json.dumps({"json_packet": str(json_path), "markdown_packet": str(md_path), "pr_ready": pr_ready}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
