"""Apply drafted fixes, routed by governance mode.

* ``standard_pr``: write edits into a working tree, create a branch, commit, and
  open a PR via ``gh`` (never merge). The PR body carries the evidence table.
* ``canon_promotion_queue``: never touch canon content; emit the drift artifacts
  (quarantine draft + DRIFT_LOG.md append + promotion-queue append).

``execute`` defaults to a dry run: it reports exactly what it *would* do and
writes no files unless ``apply=True``.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from .config import RepoConfig
from .governance import build_artifacts
from .models import Finding, Status
from .planner import PlannedEdit, plan_fixes


def _apply_edits_to_tree(repo_root: str, edits: list[PlannedEdit]) -> list[str]:
    touched: list[str] = []
    by_doc: dict[str, list[PlannedEdit]] = {}
    for e in edits:
        by_doc.setdefault(e.doc_path, []).append(e)
    for doc, doc_edits in by_doc.items():
        fp = Path(repo_root) / doc
        if not fp.is_file():
            continue
        lines = fp.read_text(encoding="utf-8").splitlines()
        for e in doc_edits:
            idx = e.line - 1
            if 0 <= idx < len(lines) and lines[idx].strip() == e.old_text.strip():
                lines[idx] = lines[idx].replace(e.old_text.strip(), e.new_text.strip())
        fp.write_text("\n".join(lines) + "\n", encoding="utf-8")
        touched.append(doc)
    return touched


def _pr_body(edits: list[PlannedEdit]) -> str:
    rows = ["| claim | doc-claimed | observed | evidence | method |",
            "|---|---|---|---|---|"]
    for e in edits:
        ev = e.evidence
        loc = ", ".join(ev.get("files", []))
        sha = (ev.get("sha") or "")[:12]
        method = ev.get("method", "")
        claimed = e.old_text[:60].replace("|", "\\|")
        rows.append(
            f"| {e.doc_path}:{e.line} | `{claimed}` | "
            f"`{(e.new_text[:60]).replace('|', '\\|')}` | {loc}@{sha} | {method} |"
        )
    return (
        "## Doc staleness auditor — evidence-backed corrections\n\n"
        "Every row was verified against **primary ground truth** (git tree / "
        "actual source content / config files), never doc-to-doc.\n\n"
        + "\n".join(rows)
        + "\n\n_Generated by `tools/doc_staleness_auditor`. Do not merge without review._\n"
    )


def execute(
    findings: list[Finding],
    cfg: RepoConfig,
    repo_root: str,
    apply: bool = False,
    branch: str | None = None,
) -> dict:
    edits = plan_fixes(findings)
    stale = [f for f in findings if f.status is Status.STALE]

    if cfg.governance_mode == "canon_promotion_queue":
        arts = build_artifacts(edits, cfg)
        result = {
            "mode": cfg.governance_mode,
            "stale_count": len(stale),
            "quarantine_path": arts.quarantine_path,
            "drift_log_path": cfg.drift_log_path,
            "promotion_queue_path": cfg.promotion_queue_path,
            "applied": False,
        }
        if apply:
            _write_governance(repo_root, cfg, arts)
            result["applied"] = True
        else:
            result["preview"] = {
                "quarantine_body": arts.quarantine_body,
                "drift_log_entry": arts.drift_log_entry,
                "promotion_queue_entry": arts.promotion_queue_entry,
            }
        return result

    # standard_pr
    br = branch or "doc-audit/staleness-fixes"
    result = {
        "mode": "standard_pr",
        "stale_count": len(stale),
        "edit_count": len(edits),
        "branch": br,
        "applied": False,
        "pr_body": _pr_body(edits),
    }
    if apply:
        _git(repo_root, "checkout", "-B", br)
        touched = _apply_edits_to_tree(repo_root, edits)
        if touched:
            _git(repo_root, "add", *touched)
            _git(repo_root, "commit", "-m",
                 "docs: apply evidence-backed staleness corrections (doc-audit)")
        result["touched"] = touched
        result["applied"] = bool(touched)
    return result


def _write_governance(repo_root: str, cfg: RepoConfig, arts) -> None:
    root = Path(repo_root)
    qp = root / arts.quarantine_path
    qp.parent.mkdir(parents=True, exist_ok=True)
    qp.write_text(arts.quarantine_body, encoding="utf-8")
    _append(root / cfg.drift_log_path, arts.drift_log_entry)
    _append(root / cfg.promotion_queue_path, arts.promotion_queue_entry)


def _append(path: Path, text: str) -> None:
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(existing + text, encoding="utf-8")


def _git(root: str, *args: str) -> str:
    proc = subprocess.run(["git", "-C", root, *args], capture_output=True, text=True, check=False)  # noqa: S603, S607
    if proc.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout
